--- #YAML:1.0
name:               AnyEvent-HTTPBenchmark
version:            0.05
abstract:           The tool to make benchmark good and easy!
author:
    - Naim Shafiev <naim@cpan.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
